### ISSUE TITLE
unable to build docker image for 2.8.0 octo-board

### ISSUE THREAD

**Issue by papapillon** [Zorin95670/octo-board#16]
missing # for '## New features'  section in CHANGELOG (in the tag 2.8.0)

**Comment by Zorin95670** [comment]
Hi, thank's for your report, I will fix it and notify you asap.

**Comment by Zorin95670** [comment]
It fix in 2.8.1 version of octo-board and in 1.4.1 version of octo.

**Comment by Zorin95670** [comment]
Please wait octo version 1.5.0 to deploy all, I make some mistake on octo-spy and octo-board. All will fix in octo 1.5.0
