### ISSUE TITLE
Board does not insert the "order" query parameter when sorting

### ISSUE THREAD

**Issue by Malizor** [Zorin95670/octo-board#9]
On the "historic" page, clicking on column titles only insert the "sort" query parameter (with "asc" or "desc" value).
Without inserting the "order" parameter to select the actual field to sort, this is kind of useless :)

**Comment by Zorin95670** [comment]
Thanks for your report. It will fix on next release.

I notice you with the version number :).

**Comment by Zorin95670** [comment]
it will fix on octo-board 2.6.0 version. I notify you when 2.6.0 it include in octo release :)

**Comment by Zorin95670** [comment]
Octo version 1.3.0 was release and fix this issue.
